---
AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: false
  Exclude:
    - "**/bin/**/*"
    - "**/node_modules/**/*"
    - "**/tmp/**/*"
    - "db/schema.rb"
    - "**/.delivery/**/*"
  ExtraDetails: true
  TargetRubyVersion: 2.5

#################################### Layout ####################################

################################### Linting ####################################

################################### Metrics ####################################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

#################################### Naming ####################################

################################# Performance ##################################

#################################### Rails #####################################

################################### Security ###################################

#################################### Style #####################################

Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW
    - NOTE

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

################################### Bundler ####################################

################################### Gemspec ####################################
